-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

create policy "Public Insert Access" 
on storage.objects for 
insert with check(
    bucket_id = 'jsonl'::text AND
    auth.role() = 'authenticated' AND
    ((storage.foldername(name))[1] = (auth.uid())::text) 
);

create policy "Public Select Access" 
 on storage.objects for select
 using ( 
    bucket_id = 'jsonl'::text AND
    auth.role() = 'authenticated' AND
    ((storage.foldername(name))[1] = (auth.uid())::text) 
);
