-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.jsonl_id(
	this_file_name text)
    RETURNS text
    LANGUAGE 'sql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
   select obj.id
   from storage.objects obj
   where obj.bucket_id = 'jsonl' and obj.name = this_file_name
$BODY$;

ALTER FUNCTION public.jsonl_id(text)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.jsonl_id(text) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.jsonl_id(text) TO anon;

GRANT EXECUTE ON FUNCTION public.jsonl_id(text) TO authenticated;

GRANT EXECUTE ON FUNCTION public.jsonl_id(text) TO postgres;

GRANT EXECUTE ON FUNCTION public.jsonl_id(text) TO service_role;
